<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>arabasorgula</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- Display name -->
    <ApplicationTitle>arabasorgula</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.arabasorgula</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Required for C# Hot Reload -->
    <!-- <UseInterpreter Condition="'$(Configuration)' == 'Debug'">True</UseInterpreter> -->
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">28.0</SupportedOSPlatformVersion>
    <DefineConstants>DEMO_APP</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <EmbedAssembliesIntoApk>false</EmbedAssembliesIntoApk>
    <_MauiForceXamlCForDebug>false</_MauiForceXamlCForDebug>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0-ios|AnyCPU'">
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0-ios|AnyCPU'">
    <CreatePackage>false</CreatePackage>
  </PropertyGroup>
  <ItemGroup>
    <!-- Images -->
    <MauiImage Include="Resources\Images\*" />
    <MauiImage Include="Resources\Images\TabIcons\*" BaseSize="28,28" />
    <!-- Custom Fonts -->
    <MauiFont Include="Resources\Fonts\**\*.ttf" />
    <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
    <MauiImage Include="Resources\Images\SocialMediaLogos\*" />
    <!-- App Icon -->
    <MauiIcon Include="Resources\appicon.svg" />
    <!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\splash.svg" Color="#da4a3e" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="ViewModels\Dashboards\Data\Dashboards.json" />
    <None Remove="ViewModels\ExplorerFlow\Data\ExplorerFlow.json" />
    <None Remove="ViewModels\Messaging\Data\Messages.json" />
    <None Remove="ViewModels\Navigation\Data\Navigation.json" />
    <None Remove="ViewModels\Onboardings\Data\Onboardings.json" />
    <None Remove="ViewModels\Paywall\Data\Paywall.json" />
    <None Remove="ViewModels\Social\Data\Social.json" />
    <None Remove="GrialLicense" />
    <None Remove="ViewModels\Articles\Data\Articles.json" />
    <None Remove="ViewModels\Theme\Data\Theme.json" />
    <None Remove="ViewModels\Ecommerce\Data\Ecommerce.json" />
    <None Remove="ViewModels\EcommerceFlow\Data\EcommerceFlow.json" />
    <None Remove="ViewModels\MessageFlow\Data\MessageFlow.json" />
    <None Remove="ViewModels\DataViz\Data\DataViz.json" />
    <None Remove="ViewModels\FoodPlacesFlow\Data\FoodPlacesFlow.json" />
    <None Remove="ViewModels\MoviesFlow\Data\MoviesFlow.json" />
    <None Remove="ViewModels\SmartHomeFlow\Data\SmartHome.json" />
    <None Remove="ViewModels\NewsFlow\Data\News.json" />
    <None Remove="ViewModels\WizardFlow\Data\WizardFlow.json" />
    <None Remove="ViewModels\QuizFlow\Data\Quiz.json" />
    <None Remove="ViewModels\Settings\Data\Settings.json" />
    <None Remove="ViewModels\Forms\Data\Forms.json" />
    <None Remove="ViewModels\TasksFlow\Data\TasksFlow.json" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="ViewModels\Dashboards\Data\Dashboards.json" />
    <EmbeddedResource Include="ViewModels\ExplorerFlow\Data\ExplorerFlow.json" />
    <EmbeddedResource Include="ViewModels\Messaging\Data\Messages.json" />
    <EmbeddedResource Include="ViewModels\Navigation\Data\Navigation.json" />
    <EmbeddedResource Include="ViewModels\Onboardings\Data\Onboardings.json" />
    <EmbeddedResource Include="ViewModels\Paywall\Data\Paywall.json" />
    <EmbeddedResource Include="ViewModels\Social\Data\Social.json" />
    <EmbeddedResource Include="GrialLicense" />
    <EmbeddedResource Include="ViewModels\Articles\Data\Articles.json" />
    <EmbeddedResource Include="ViewModels\Theme\Data\Theme.json" />
    <EmbeddedResource Include="ViewModels\Ecommerce\Data\Ecommerce.json" />
    <EmbeddedResource Include="ViewModels\EcommerceFlow\Data\EcommerceFlow.json" />
    <EmbeddedResource Include="ViewModels\MessageFlow\Data\MessageFlow.json" />
    <EmbeddedResource Include="ViewModels\DataViz\Data\DataViz.json" />
    <EmbeddedResource Include="ViewModels\FoodPlacesFlow\Data\FoodPlacesFlow.json" />
    <EmbeddedResource Include="ViewModels\MoviesFlow\Data\MoviesFlow.json" />
    <EmbeddedResource Include="ViewModels\SmartHomeFlow\Data\SmartHome.json" />
    <EmbeddedResource Include="ViewModels\NewsFlow\Data\News.json" />
    <EmbeddedResource Include="ViewModels\WizardFlow\Data\WizardFlow.json" />
    <EmbeddedResource Include="ViewModels\QuizFlow\Data\Quiz.json" />
    <EmbeddedResource Include="ViewModels\Settings\Data\Settings.json" />
    <EmbeddedResource Include="ViewModels\Forms\Data\Forms.json" />
    <EmbeddedResource Include="ViewModels\TasksFlow\Data\TasksFlow.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.30" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.30" />
    <PackageReference Include="CommunityToolkit.Maui" Version="13.0.0" />
    <PackageReference Include="UXDivers.GrialMaui" Version="4.4.127" />
    <PackageReference Include="UXDivers.GrialMaui.Maps" Version="4.4.127" />
    <PackageReference Include="UXDivers.Popups.Maui" Version="0.9.2" />
  </ItemGroup>
  <ItemGroup Condition=" $(TargetFramework.Contains(-ios)) ">
    <Compile Remove="Resources\Raw\local_video.mp4" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="ViewModels\DemoApp\Resx\DemoAppResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DemoAppResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resx\AppResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AppResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="ViewModels\DemoApp\Resx\DemoAppResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DemoAppResources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>arabasorgula</CustomToolNamespace>
      <LogicalName>arabasorgula.DemoAppResources.resources</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Update="Resx\AppResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="ViewModels\DemoApp\Resx\DemoAppResources.Designer.cs">
      <DependentUpon>DemoAppResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resx\AppResources.Designer.cs">
      <DependentUpon>AppResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>