//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UXDivers.Grial;
namespace arabasorgula {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DemoAppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoAppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("arabasorgula.DemoAppResources", typeof(DemoAppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string PageTitleThemesPreview {
            get {
                return ResourceManager.GetString("PageTitleThemesPreview", resourceCulture);
            }
        }
        
        public static string StringApply {
            get {
                return ResourceManager.GetString("StringApply", resourceCulture);
            }
        }
        
        public static string StringApplied {
            get {
                return ResourceManager.GetString("StringApplied", resourceCulture);
            }
        }
        
        public static string ScreenCount {
            get {
                return ResourceManager.GetString("ScreenCount", resourceCulture);
            }
        }
        
        public static string MainMenuWhatsNew {
            get {
                return ResourceManager.GetString("MainMenuWhatsNew", resourceCulture);
            }
        }
        
        public static string MainMenuControlsAndFeatures {
            get {
                return ResourceManager.GetString("MainMenuControlsAndFeatures", resourceCulture);
            }
        }
        
        public static string MainMenuCustomControls {
            get {
                return ResourceManager.GetString("MainMenuCustomControls", resourceCulture);
            }
        }
        
        public static string MainMenuDashboard {
            get {
                return ResourceManager.GetString("MainMenuDashboard", resourceCulture);
            }
        }
        
        public static string MainMenuIcons {
            get {
                return ResourceManager.GetString("MainMenuIcons", resourceCulture);
            }
        }
        
        public static string MainMenuGrialThemes {
            get {
                return ResourceManager.GetString("MainMenuGrialThemes", resourceCulture);
            }
        }
        
        public static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        public static string DemoAppPageTitleAbout {
            get {
                return ResourceManager.GetString("DemoAppPageTitleAbout", resourceCulture);
            }
        }
        
        public static string StringGetGrial {
            get {
                return ResourceManager.GetString("StringGetGrial", resourceCulture);
            }
        }
        
        public static string StringGetGrialNow {
            get {
                return ResourceManager.GetString("StringGetGrialNow", resourceCulture);
            }
        }
        
        public static string ButtonBrowseOurSamples {
            get {
                return ResourceManager.GetString("ButtonBrowseOurSamples", resourceCulture);
            }
        }
        
        public static string ButtonSeeOurWalkThrough {
            get {
                return ResourceManager.GetString("ButtonSeeOurWalkThrough", resourceCulture);
            }
        }
        
        public static string FlowDescriptionMovies {
            get {
                return ResourceManager.GetString("FlowDescriptionMovies", resourceCulture);
            }
        }
        
        public static string FlowDescriptionEcommerce {
            get {
                return ResourceManager.GetString("FlowDescriptionEcommerce", resourceCulture);
            }
        }
        
        public static string FlowDescriptionTasks {
            get {
                return ResourceManager.GetString("FlowDescriptionTasks", resourceCulture);
            }
        }
        
        public static string FlowDescriptionMessages {
            get {
                return ResourceManager.GetString("FlowDescriptionMessages", resourceCulture);
            }
        }
        
        public static string FlowDescriptionExplorerFiles {
            get {
                return ResourceManager.GetString("FlowDescriptionExplorerFiles", resourceCulture);
            }
        }
        
        public static string FlowDescriptionFoodPlaces {
            get {
                return ResourceManager.GetString("FlowDescriptionFoodPlaces", resourceCulture);
            }
        }
        
        public static string FlowDescriptionSmartHome {
            get {
                return ResourceManager.GetString("FlowDescriptionSmartHome", resourceCulture);
            }
        }
        
        public static string FlowDescriptionMatch {
            get {
                return ResourceManager.GetString("FlowDescriptionMatch", resourceCulture);
            }
        }
        
        public static string FlowDescriptionWizard {
            get {
                return ResourceManager.GetString("FlowDescriptionWizard", resourceCulture);
            }
        }
        
        public static string FlowDescriptionQuiz {
            get {
                return ResourceManager.GetString("FlowDescriptionQuiz", resourceCulture);
            }
        }
        
        public static string UsersAnalyticsPageDescription {
            get {
                return ResourceManager.GetString("UsersAnalyticsPageDescription", resourceCulture);
            }
        }
        
        public static string TrafficAnalyticsPageDescription {
            get {
                return ResourceManager.GetString("TrafficAnalyticsPageDescription", resourceCulture);
            }
        }
        
        public static string WalletPiePageDescription {
            get {
                return ResourceManager.GetString("WalletPiePageDescription", resourceCulture);
            }
        }
        
        public static string WalletAlternativePageDescription {
            get {
                return ResourceManager.GetString("WalletAlternativePageDescription", resourceCulture);
            }
        }
        
        public static string PowerUsagePageDescription {
            get {
                return ResourceManager.GetString("PowerUsagePageDescription", resourceCulture);
            }
        }
        
        public static string WebsiteTrafficReportPageDescription {
            get {
                return ResourceManager.GetString("WebsiteTrafficReportPageDescription", resourceCulture);
            }
        }
        
        public static string DocumentTimelinePageDescription {
            get {
                return ResourceManager.GetString("DocumentTimelinePageDescription", resourceCulture);
            }
        }
        
        public static string TimelinePageDescription {
            get {
                return ResourceManager.GetString("TimelinePageDescription", resourceCulture);
            }
        }
        
        public static string ProfilePageTimelinePageDescription {
            get {
                return ResourceManager.GetString("ProfilePageTimelinePageDescription", resourceCulture);
            }
        }
        
        public static string SocialPageDescription {
            get {
                return ResourceManager.GetString("SocialPageDescription", resourceCulture);
            }
        }
        
        public static string SocialVariantPageDescription {
            get {
                return ResourceManager.GetString("SocialVariantPageDescription", resourceCulture);
            }
        }
        
        public static string SocialCardPageDescription {
            get {
                return ResourceManager.GetString("SocialCardPageDescription", resourceCulture);
            }
        }
        
        public static string FullHeaderArticlePagePageDescription {
            get {
                return ResourceManager.GetString("FullHeaderArticlePagePageDescription", resourceCulture);
            }
        }
        
        public static string ArticlesClassicViewPageDescription {
            get {
                return ResourceManager.GetString("ArticlesClassicViewPageDescription", resourceCulture);
            }
        }
        
        public static string ArticlesColumnPageDescription {
            get {
                return ResourceManager.GetString("ArticlesColumnPageDescription", resourceCulture);
            }
        }
        
        public static string ArticleDetailPageDescription {
            get {
                return ResourceManager.GetString("ArticleDetailPageDescription", resourceCulture);
            }
        }
        
        public static string ArticlesListPageDescription {
            get {
                return ResourceManager.GetString("ArticlesListPageDescription", resourceCulture);
            }
        }
        
        public static string ArticlesFeedPageDescription {
            get {
                return ResourceManager.GetString("ArticlesFeedPageDescription", resourceCulture);
            }
        }
        
        public static string DashboardCarouselPageDescription {
            get {
                return ResourceManager.GetString("DashboardCarouselPageDescription", resourceCulture);
            }
        }
        
        public static string DashboardSwipeableHeaderPageDescription {
            get {
                return ResourceManager.GetString("DashboardSwipeableHeaderPageDescription", resourceCulture);
            }
        }
        
        public static string NavigationCardsDescriptionListPageDescription {
            get {
                return ResourceManager.GetString("NavigationCardsDescriptionListPageDescription", resourceCulture);
            }
        }
        
        public static string ExplorerListPageDescription {
            get {
                return ResourceManager.GetString("ExplorerListPageDescription", resourceCulture);
            }
        }
        
        public static string FoodPlacesMainPageDescription {
            get {
                return ResourceManager.GetString("FoodPlacesMainPageDescription", resourceCulture);
            }
        }
        
        public static string FoodPlacesMapPageDescription {
            get {
                return ResourceManager.GetString("FoodPlacesMapPageDescription", resourceCulture);
            }
        }
        
        public static string FoodPlacesDishReviewPageDescription {
            get {
                return ResourceManager.GetString("FoodPlacesDishReviewPageDescription", resourceCulture);
            }
        }
        
        public static string SmartHomeMainPageDescription {
            get {
                return ResourceManager.GetString("SmartHomeMainPageDescription", resourceCulture);
            }
        }
        
        public static string SmartHomeRoomPageDescription {
            get {
                return ResourceManager.GetString("SmartHomeRoomPageDescription", resourceCulture);
            }
        }
        
        public static string SmartHomeLightSettingsPageDescription {
            get {
                return ResourceManager.GetString("SmartHomeLightSettingsPageDescription", resourceCulture);
            }
        }
        
        public static string MoviesMainPageDescription {
            get {
                return ResourceManager.GetString("MoviesMainPageDescription", resourceCulture);
            }
        }
        
        public static string MovieDetailPageDescription {
            get {
                return ResourceManager.GetString("MovieDetailPageDescription", resourceCulture);
            }
        }
        
        public static string ListWithColumnsPageDescription {
            get {
                return ResourceManager.GetString("ListWithColumnsPageDescription", resourceCulture);
            }
        }
        
        public static string ListWithColumnsVariantPageDescription {
            get {
                return ResourceManager.GetString("ListWithColumnsVariantPageDescription", resourceCulture);
            }
        }
        
        public static string DashboardCardsPageDescription {
            get {
                return ResourceManager.GetString("DashboardCardsPageDescription", resourceCulture);
            }
        }
        
        public static string DashboardMultipleTilesPageDescription {
            get {
                return ResourceManager.GetString("DashboardMultipleTilesPageDescription", resourceCulture);
            }
        }
        
        public static string WizardMainPageDescription {
            get {
                return ResourceManager.GetString("WizardMainPageDescription", resourceCulture);
            }
        }
        
        public static string WizardVariantMainPageDescription {
            get {
                return ResourceManager.GetString("WizardVariantMainPageDescription", resourceCulture);
            }
        }
        
        public static string MatchMainPageDescription {
            get {
                return ResourceManager.GetString("MatchMainPageDescription", resourceCulture);
            }
        }
        
        public static string MatchPageDescription {
            get {
                return ResourceManager.GetString("MatchPageDescription", resourceCulture);
            }
        }
        
        public static string IconsDashboardPageDescription {
            get {
                return ResourceManager.GetString("IconsDashboardPageDescription", resourceCulture);
            }
        }
        
        public static string FlatDashboardPageDescription {
            get {
                return ResourceManager.GetString("FlatDashboardPageDescription", resourceCulture);
            }
        }
        
        public static string ImagesDashboardPageDescription {
            get {
                return ResourceManager.GetString("ImagesDashboardPageDescription", resourceCulture);
            }
        }
        
        public static string VideoListPreviewPageDescription {
            get {
                return ResourceManager.GetString("VideoListPreviewPageDescription", resourceCulture);
            }
        }
        
        public static string NavigationCardsListPageDescription {
            get {
                return ResourceManager.GetString("NavigationCardsListPageDescription", resourceCulture);
            }
        }
        
        public static string EmptyStatePageDescription {
            get {
                return ResourceManager.GetString("EmptyStatePageDescription", resourceCulture);
            }
        }
        
        public static string WelcomePageDescription {
            get {
                return ResourceManager.GetString("WelcomePageDescription", resourceCulture);
            }
        }
        
        public static string StartPageDescription {
            get {
                return ResourceManager.GetString("StartPageDescription", resourceCulture);
            }
        }
        
        public static string StartVariantPageDescription {
            get {
                return ResourceManager.GetString("StartVariantPageDescription", resourceCulture);
            }
        }
        
        public static string NotificationsPageDescription {
            get {
                return ResourceManager.GetString("NotificationsPageDescription", resourceCulture);
            }
        }
        
        public static string NavigationFlatListPageDescription {
            get {
                return ResourceManager.GetString("NavigationFlatListPageDescription", resourceCulture);
            }
        }
        
        public static string NavigationListWithImagesPageDescription {
            get {
                return ResourceManager.GetString("NavigationListWithImagesPageDescription", resourceCulture);
            }
        }
        
        public static string NavigationListWithIconsPageDescription {
            get {
                return ResourceManager.GetString("NavigationListWithIconsPageDescription", resourceCulture);
            }
        }
        
        public static string TabbedLoginPageDescription {
            get {
                return ResourceManager.GetString("TabbedLoginPageDescription", resourceCulture);
            }
        }
        
        public static string SimpleSignUpPageDescription {
            get {
                return ResourceManager.GetString("SimpleSignUpPageDescription", resourceCulture);
            }
        }
        
        public static string SimpleLoginPageDescription {
            get {
                return ResourceManager.GetString("SimpleLoginPageDescription", resourceCulture);
            }
        }
        
        public static string LoginPageDescription {
            get {
                return ResourceManager.GetString("LoginPageDescription", resourceCulture);
            }
        }
        
        public static string SignUpPageDescription {
            get {
                return ResourceManager.GetString("SignUpPageDescription", resourceCulture);
            }
        }
        
        public static string PasswordRecoveryPageDescription {
            get {
                return ResourceManager.GetString("PasswordRecoveryPageDescription", resourceCulture);
            }
        }
        
        public static string ProductImageFullScreenPageDescription {
            get {
                return ResourceManager.GetString("ProductImageFullScreenPageDescription", resourceCulture);
            }
        }
        
        public static string ProductsCatalogPageDescription {
            get {
                return ResourceManager.GetString("ProductsCatalogPageDescription", resourceCulture);
            }
        }
        
        public static string ProductOrderPageDescription {
            get {
                return ResourceManager.GetString("ProductOrderPageDescription", resourceCulture);
            }
        }
        
        public static string ProductsGridPageDescription {
            get {
                return ResourceManager.GetString("ProductsGridPageDescription", resourceCulture);
            }
        }
        
        public static string ProductsGridVariantPageDescription {
            get {
                return ResourceManager.GetString("ProductsGridVariantPageDescription", resourceCulture);
            }
        }
        
        public static string ProductItemViewPageDescription {
            get {
                return ResourceManager.GetString("ProductItemViewPageDescription", resourceCulture);
            }
        }
        
        public static string ProductsCarouselPageDescription {
            get {
                return ResourceManager.GetString("ProductsCarouselPageDescription", resourceCulture);
            }
        }
        
        public static string WalkthroughPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughPageDescription", resourceCulture);
            }
        }
        
        public static string WalkthroughFlatPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughFlatPageDescription", resourceCulture);
            }
        }
        
        public static string WalkthroughVariantPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughVariantPageDescription", resourceCulture);
            }
        }
        
        public static string ChatTimelinePageDescription {
            get {
                return ResourceManager.GetString("ChatTimelinePageDescription", resourceCulture);
            }
        }
        
        public static string RecentChatListPageDescription {
            get {
                return ResourceManager.GetString("RecentChatListPageDescription", resourceCulture);
            }
        }
        
        public static string MessagesListPageDescription {
            get {
                return ResourceManager.GetString("MessagesListPageDescription", resourceCulture);
            }
        }
        
        public static string ChatMessagesListPageDescription {
            get {
                return ResourceManager.GetString("ChatMessagesListPageDescription", resourceCulture);
            }
        }
        
        public static string TabControlCustomSamplePageDescription {
            get {
                return ResourceManager.GetString("TabControlCustomSamplePageDescription", resourceCulture);
            }
        }
        
        public static string TabControlAndroidSamplePageDescription {
            get {
                return ResourceManager.GetString("TabControlAndroidSamplePageDescription", resourceCulture);
            }
        }
        
        public static string TabControliOSSamplePageDescription {
            get {
                return ResourceManager.GetString("TabControliOSSamplePageDescription", resourceCulture);
            }
        }
        
        public static string TabControlBottomPlacementSamplePageDescription {
            get {
                return ResourceManager.GetString("TabControlBottomPlacementSamplePageDescription", resourceCulture);
            }
        }
        
        public static string TabPageDescription {
            get {
                return ResourceManager.GetString("TabPageDescription", resourceCulture);
            }
        }
        
        public static string DemoSettingsPageDescription {
            get {
                return ResourceManager.GetString("DemoSettingsPageDescription", resourceCulture);
            }
        }
        
        public static string GenericAboutPageDescription {
            get {
                return ResourceManager.GetString("GenericAboutPageDescription", resourceCulture);
            }
        }
        
        public static string RichAboutPageDescription {
            get {
                return ResourceManager.GetString("RichAboutPageDescription", resourceCulture);
            }
        }
        
        public static string CustomSettingsPageDescription {
            get {
                return ResourceManager.GetString("CustomSettingsPageDescription", resourceCulture);
            }
        }
        
        public static string FAQsPageDescription {
            get {
                return ResourceManager.GetString("FAQsPageDescription", resourceCulture);
            }
        }
        
        public static string CustomActivityIndicatorPageDescription {
            get {
                return ResourceManager.GetString("CustomActivityIndicatorPageDescription", resourceCulture);
            }
        }
        
        public static string ResponsiveHelpersPageDescription {
            get {
                return ResourceManager.GetString("ResponsiveHelpersPageDescription", resourceCulture);
            }
        }
        
        public static string IconsPageDescription {
            get {
                return ResourceManager.GetString("IconsPageDescription", resourceCulture);
            }
        }
        
        public static string ThemeOverviewPageDescription {
            get {
                return ResourceManager.GetString("ThemeOverviewPageDescription", resourceCulture);
            }
        }
        
        public static string CustomRenderersPageDescription {
            get {
                return ResourceManager.GetString("CustomRenderersPageDescription", resourceCulture);
            }
        }
        
        public static string SettingsPageDescription {
            get {
                return ResourceManager.GetString("SettingsPageDescription", resourceCulture);
            }
        }
        
        public static string PerformanceDashboardMainPageDescription {
            get {
                return ResourceManager.GetString("PerformanceDashboardMainPageDescription", resourceCulture);
            }
        }
        
        public static string EmployeePerformanceDashboardPageDescription {
            get {
                return ResourceManager.GetString("EmployeePerformanceDashboardPageDescription", resourceCulture);
            }
        }
        
        public static string EmployeeProfileDashboardPageDescription {
            get {
                return ResourceManager.GetString("EmployeeProfileDashboardPageDescription", resourceCulture);
            }
        }
        
        public static string AddContactPageDescription {
            get {
                return ResourceManager.GetString("AddContactPageDescription", resourceCulture);
            }
        }
        
        public static string ContactSimpleDetailPageDescription {
            get {
                return ResourceManager.GetString("ContactSimpleDetailPageDescription", resourceCulture);
            }
        }
        
        public static string ContactDetailPageDescription {
            get {
                return ResourceManager.GetString("ContactDetailPageDescription", resourceCulture);
            }
        }
        
        public static string ChatMessagesPageDescription {
            get {
                return ResourceManager.GetString("ChatMessagesPageDescription", resourceCulture);
            }
        }
        
        public static string ChatMainPageDescription {
            get {
                return ResourceManager.GetString("ChatMainPageDescription", resourceCulture);
            }
        }
        
        public static string CardArticlePageDescription {
            get {
                return ResourceManager.GetString("CardArticlePageDescription", resourceCulture);
            }
        }
        
        public static string ArticlesBrowserPageDescription {
            get {
                return ResourceManager.GetString("ArticlesBrowserPageDescription", resourceCulture);
            }
        }
        
        public static string FeaturedMoviesPageDescription {
            get {
                return ResourceManager.GetString("FeaturedMoviesPageDescription", resourceCulture);
            }
        }
        
        public static string CurvedHeaderArticlePageDescription {
            get {
                return ResourceManager.GetString("CurvedHeaderArticlePageDescription", resourceCulture);
            }
        }
        
        public static string OrganizationFormPageDescription {
            get {
                return ResourceManager.GetString("OrganizationFormPageDescription", resourceCulture);
            }
        }
        
        public static string FullBackgroundLoginPageDescription {
            get {
                return ResourceManager.GetString("FullBackgroundLoginPageDescription", resourceCulture);
            }
        }
        
        public static string FullBackgroundSignupPageDescription {
            get {
                return ResourceManager.GetString("FullBackgroundSignupPageDescription", resourceCulture);
            }
        }
        
        public static string EmployeeFormPageDescription {
            get {
                return ResourceManager.GetString("EmployeeFormPageDescription", resourceCulture);
            }
        }
        
        public static string EcommerceMainPageDescription {
            get {
                return ResourceManager.GetString("EcommerceMainPageDescription", resourceCulture);
            }
        }
        
        public static string ProductDetailPageDescription {
            get {
                return ResourceManager.GetString("ProductDetailPageDescription", resourceCulture);
            }
        }
        
        public static string OrderConfirmationPageDescription {
            get {
                return ResourceManager.GetString("OrderConfirmationPageDescription", resourceCulture);
            }
        }
        
        public static string CheckoutPageDescription {
            get {
                return ResourceManager.GetString("CheckoutPageDescription", resourceCulture);
            }
        }
        
        public static string VideoCarouselHighlightsPageDescription {
            get {
                return ResourceManager.GetString("VideoCarouselHighlightsPageDescription", resourceCulture);
            }
        }
        
        public static string WalkthroughGradientPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughGradientPageDescription", resourceCulture);
            }
        }
        
        public static string WalkthroughImagePageDescription {
            get {
                return ResourceManager.GetString("WalkthroughImagePageDescription", resourceCulture);
            }
        }
        
        public static string WalkthroughMinimalPageDescription {
            get {
                return ResourceManager.GetString("WalkthroughMinimalPageDescription", resourceCulture);
            }
        }
        
        public static string PopupsPageDescription {
            get {
                return ResourceManager.GetString("PopupsPageDescription", resourceCulture);
            }
        }
        
        public static string ShippingDetailPageDescription {
            get {
                return ResourceManager.GetString("ShippingDetailPageDescription", resourceCulture);
            }
        }
        
        public static string TaskBrowserPageDescription {
            get {
                return ResourceManager.GetString("TaskBrowserPageDescription", resourceCulture);
            }
        }
        
        public static string TaskOverviewPageDescription {
            get {
                return ResourceManager.GetString("TaskOverviewPageDescription", resourceCulture);
            }
        }
        
        public static string PricingPlanAPageDescription {
            get {
                return ResourceManager.GetString("PricingPlanAPageDescription", resourceCulture);
            }
        }
        
        public static string PricingPlanBPageDescription {
            get {
                return ResourceManager.GetString("PricingPlanBPageDescription", resourceCulture);
            }
        }
        
        public static string PricingPlanCPageDescription {
            get {
                return ResourceManager.GetString("PricingPlanCPageDescription", resourceCulture);
            }
        }
        
        public static string PricingPlanDPageDescription {
            get {
                return ResourceManager.GetString("PricingPlanDPageDescription", resourceCulture);
            }
        }
        
        public static string NewsWelcomePageDescription {
            get {
                return ResourceManager.GetString("NewsWelcomePageDescription", resourceCulture);
            }
        }
        
        public static string NewsLoginPageDescription {
            get {
                return ResourceManager.GetString("NewsLoginPageDescription", resourceCulture);
            }
        }
        
        public static string NewsSignUpPageDescription {
            get {
                return ResourceManager.GetString("NewsSignUpPageDescription", resourceCulture);
            }
        }
        
        public static string NewsMainPageDescription {
            get {
                return ResourceManager.GetString("NewsMainPageDescription", resourceCulture);
            }
        }
        
        public static string NewsMembershipPageDescription {
            get {
                return ResourceManager.GetString("NewsMembershipPageDescription", resourceCulture);
            }
        }
        
        public static string NewsListPageDescription {
            get {
                return ResourceManager.GetString("NewsListPageDescription", resourceCulture);
            }
        }
        
        public static string NewsSourcesPageDescription {
            get {
                return ResourceManager.GetString("NewsSourcesPageDescription", resourceCulture);
            }
        }
        
        public static string NewsTopicsPageDescription {
            get {
                return ResourceManager.GetString("NewsTopicsPageDescription", resourceCulture);
            }
        }
        
        public static string NewsSourceProfilePageDescription {
            get {
                return ResourceManager.GetString("NewsSourceProfilePageDescription", resourceCulture);
            }
        }
        
        public static string NewsDetailPageDescription {
            get {
                return ResourceManager.GetString("NewsDetailPageDescription", resourceCulture);
            }
        }
        
        public static string NewsMyProfilePageDescription {
            get {
                return ResourceManager.GetString("NewsMyProfilePageDescription", resourceCulture);
            }
        }
        
        public static string QuizDashboardPageDescription {
            get {
                return ResourceManager.GetString("QuizDashboardPageDescription", resourceCulture);
            }
        }
        
        public static string QuizGamePageDescription {
            get {
                return ResourceManager.GetString("QuizGamePageDescription", resourceCulture);
            }
        }
        
        public static string QuizProfileAchievementsPageDescription {
            get {
                return ResourceManager.GetString("QuizProfileAchievementsPageDescription", resourceCulture);
            }
        }
        
        public static string QuizResultsPageDescription {
            get {
                return ResourceManager.GetString("QuizResultsPageDescription", resourceCulture);
            }
        }
        
        public static string MySettingsPageDescription {
            get {
                return ResourceManager.GetString("MySettingsPageDescription", resourceCulture);
            }
        }
        
        public static string ProfileSettingsPageDescription {
            get {
                return ResourceManager.GetString("ProfileSettingsPageDescription", resourceCulture);
            }
        }
        
        public static string AppPreferencesPageDescription {
            get {
                return ResourceManager.GetString("AppPreferencesPageDescription", resourceCulture);
            }
        }
        
        public static string SettingsMenuPageDescription {
            get {
                return ResourceManager.GetString("SettingsMenuPageDescription", resourceCulture);
            }
        }
        
        public static string SettingsMenuVariantPageDescription {
            get {
                return ResourceManager.GetString("SettingsMenuVariantPageDescription", resourceCulture);
            }
        }
        
        public static string FeatureRtlInvite {
            get {
                return ResourceManager.GetString("FeatureRtlInvite", resourceCulture);
            }
        }
        
        public static string FeatureI18nInvite {
            get {
                return ResourceManager.GetString("FeatureI18nInvite", resourceCulture);
            }
        }
        
        public static string FeatureI18nTitle {
            get {
                return ResourceManager.GetString("FeatureI18nTitle", resourceCulture);
            }
        }
        
        public static string FeatureI18nDescription {
            get {
                return ResourceManager.GetString("FeatureI18nDescription", resourceCulture);
            }
        }
        
        public static string FeatureRTLTitle {
            get {
                return ResourceManager.GetString("FeatureRTLTitle", resourceCulture);
            }
        }
        
        public static string FeatureRTLDescription {
            get {
                return ResourceManager.GetString("FeatureRTLDescription", resourceCulture);
            }
        }
        
        public static string FeatureDataGridTitle {
            get {
                return ResourceManager.GetString("FeatureDataGridTitle", resourceCulture);
            }
        }
        
        public static string FeatureDataGridDescription {
            get {
                return ResourceManager.GetString("FeatureDataGridDescription", resourceCulture);
            }
        }
        
        public static string FeatureCardViewTitle {
            get {
                return ResourceManager.GetString("FeatureCardViewTitle", resourceCulture);
            }
        }
        
        public static string FeatureCardViewDescription {
            get {
                return ResourceManager.GetString("FeatureCardViewDescription", resourceCulture);
            }
        }
        
        public static string FeatureVideoPlayerTitle {
            get {
                return ResourceManager.GetString("FeatureVideoPlayerTitle", resourceCulture);
            }
        }
        
        public static string FeatureVideoPlayerDescription {
            get {
                return ResourceManager.GetString("FeatureVideoPlayerDescription", resourceCulture);
            }
        }
        
        public static string FeaturePopupsTitle {
            get {
                return ResourceManager.GetString("FeaturePopupsTitle", resourceCulture);
            }
        }
        
        public static string FeaturePopupsDescription {
            get {
                return ResourceManager.GetString("FeaturePopupsDescription", resourceCulture);
            }
        }
        
        public static string FeatureCarouselViewTitle {
            get {
                return ResourceManager.GetString("FeatureCarouselViewTitle", resourceCulture);
            }
        }
        
        public static string FeatureCarouselViewDescription {
            get {
                return ResourceManager.GetString("FeatureCarouselViewDescription", resourceCulture);
            }
        }
        
        public static string FeatureAnimationsViewTitle {
            get {
                return ResourceManager.GetString("FeatureAnimationsViewTitle", resourceCulture);
            }
        }
        
        public static string FeatureAnimationsViewDescription {
            get {
                return ResourceManager.GetString("FeatureAnimationsViewDescription", resourceCulture);
            }
        }
        
        public static string FeatureGradientsViewTitle {
            get {
                return ResourceManager.GetString("FeatureGradientsViewTitle", resourceCulture);
            }
        }
        
        public static string FeatureGradientsViewDescription {
            get {
                return ResourceManager.GetString("FeatureGradientsViewDescription", resourceCulture);
            }
        }
        
        public static string FeatureGrialNavbarViewTitle {
            get {
                return ResourceManager.GetString("FeatureGrialNavbarViewTitle", resourceCulture);
            }
        }
        
        public static string FeatureGrialNavbarViewDescription {
            get {
                return ResourceManager.GetString("FeatureGrialNavbarViewDescription", resourceCulture);
            }
        }
        
        public static string FeatureCheckboxesAndRadiosTitle {
            get {
                return ResourceManager.GetString("FeatureCheckboxesAndRadiosTitle", resourceCulture);
            }
        }
        
        public static string FeatureCheckboxesAndRadiosDescription {
            get {
                return ResourceManager.GetString("FeatureCheckboxesAndRadiosDescription", resourceCulture);
            }
        }
        
        public static string FeatureTabControlTitle {
            get {
                return ResourceManager.GetString("FeatureTabControlTitle", resourceCulture);
            }
        }
        
        public static string FeatureTabControlDescription {
            get {
                return ResourceManager.GetString("FeatureTabControlDescription", resourceCulture);
            }
        }
        
        public static string FeatureRepeaterTitle {
            get {
                return ResourceManager.GetString("FeatureRepeaterTitle", resourceCulture);
            }
        }
        
        public static string FeatureRepeaterDescription {
            get {
                return ResourceManager.GetString("FeatureRepeaterDescription", resourceCulture);
            }
        }
        
        public static string FeatureWrapPanelTitle {
            get {
                return ResourceManager.GetString("FeatureWrapPanelTitle", resourceCulture);
            }
        }
        
        public static string FeatureWrapPanelDescription {
            get {
                return ResourceManager.GetString("FeatureWrapPanelDescription", resourceCulture);
            }
        }
        
        public static string FeatureGridViewTitle {
            get {
                return ResourceManager.GetString("FeatureGridViewTitle", resourceCulture);
            }
        }
        
        public static string FeatureGridViewDescription {
            get {
                return ResourceManager.GetString("FeatureGridViewDescription", resourceCulture);
            }
        }
        
        public static string FeatureIconsTitle {
            get {
                return ResourceManager.GetString("FeatureIconsTitle", resourceCulture);
            }
        }
        
        public static string FeatureIconsDescription {
            get {
                return ResourceManager.GetString("FeatureIconsDescription", resourceCulture);
            }
        }
        
        public static string FeatureGrialFlowsTitle {
            get {
                return ResourceManager.GetString("FeatureGrialFlowsTitle", resourceCulture);
            }
        }
        
        public static string FeatureGrialFlowsDescription {
            get {
                return ResourceManager.GetString("FeatureGrialFlowsDescription", resourceCulture);
            }
        }
        
        public static string FeatureSafeAreaEffectTitle {
            get {
                return ResourceManager.GetString("FeatureSafeAreaEffectTitle", resourceCulture);
            }
        }
        
        public static string FeatureSafeAreaEffectDescription {
            get {
                return ResourceManager.GetString("FeatureSafeAreaEffectDescription", resourceCulture);
            }
        }
        
        public static string FeatureCustomRenderersTitle {
            get {
                return ResourceManager.GetString("FeatureCustomRenderersTitle", resourceCulture);
            }
        }
        
        public static string FeatureCustomRenderersDescription {
            get {
                return ResourceManager.GetString("FeatureCustomRenderersDescription", resourceCulture);
            }
        }
        
        public static string FeatureResponsiveHelpersTitle {
            get {
                return ResourceManager.GetString("FeatureResponsiveHelpersTitle", resourceCulture);
            }
        }
        
        public static string FeatureResponsiveHelpersDescription {
            get {
                return ResourceManager.GetString("FeatureResponsiveHelpersDescription", resourceCulture);
            }
        }
        
        public static string FeatureChartsTitle {
            get {
                return ResourceManager.GetString("FeatureChartsTitle", resourceCulture);
            }
        }
        
        public static string FeatureChartsDescription {
            get {
                return ResourceManager.GetString("FeatureChartsDescription", resourceCulture);
            }
        }
        
        public static string FeatureAnimationLoopsTitle {
            get {
                return ResourceManager.GetString("FeatureAnimationLoopsTitle", resourceCulture);
            }
        }
        
        public static string FeatureAnimationLoopsDescription {
            get {
                return ResourceManager.GetString("FeatureAnimationLoopsDescription", resourceCulture);
            }
        }
        
        public static string FeaturePoweredBy {
            get {
                return ResourceManager.GetString("FeaturePoweredBy", resourceCulture);
            }
        }
        
        public static string GrialAboutDescription {
            get {
                return ResourceManager.GetString("GrialAboutDescription", resourceCulture);
            }
        }
        
        public static string GrialAboutMission {
            get {
                return ResourceManager.GetString("GrialAboutMission", resourceCulture);
            }
        }
        
        public static string GrialAboutTeam {
            get {
                return ResourceManager.GetString("GrialAboutTeam", resourceCulture);
            }
        }
        
        public static string GrialAboutFollowUs {
            get {
                return ResourceManager.GetString("GrialAboutFollowUs", resourceCulture);
            }
        }
        
        public static string GrialAboutEagerToHear {
            get {
                return ResourceManager.GetString("GrialAboutEagerToHear", resourceCulture);
            }
        }
        
        public static string GrialAboutSayHello {
            get {
                return ResourceManager.GetString("GrialAboutSayHello", resourceCulture);
            }
        }
        
        public static string GrialAboutGrialUses {
            get {
                return ResourceManager.GetString("GrialAboutGrialUses", resourceCulture);
            }
        }
        
        public static string GrialAboutGrialThirdParty {
            get {
                return ResourceManager.GetString("GrialAboutGrialThirdParty", resourceCulture);
            }
        }
        
        public static string GrialAboutGrialPoweredBy {
            get {
                return ResourceManager.GetString("GrialAboutGrialPoweredBy", resourceCulture);
            }
        }
        
        public static string GrialAboutGrialCommunity {
            get {
                return ResourceManager.GetString("GrialAboutGrialCommunity", resourceCulture);
            }
        }
        
        public static string GrialAboutTestimonialMiguelDeIcaza {
            get {
                return ResourceManager.GetString("GrialAboutTestimonialMiguelDeIcaza", resourceCulture);
            }
        }
        
        public static string GrialAboutTestimonialDavidOrtinau {
            get {
                return ResourceManager.GetString("GrialAboutTestimonialDavidOrtinau", resourceCulture);
            }
        }
        
        public static string WhatsNewDescription1 {
            get {
                return ResourceManager.GetString("WhatsNewDescription1", resourceCulture);
            }
        }
        
        public static string WhatsNewDescription2 {
            get {
                return ResourceManager.GetString("WhatsNewDescription2", resourceCulture);
            }
        }
        
        public static string WhatsNewDescription3 {
            get {
                return ResourceManager.GetString("WhatsNewDescription3", resourceCulture);
            }
        }
        
        public static string WhatsNewDescription4 {
            get {
                return ResourceManager.GetString("WhatsNewDescription4", resourceCulture);
            }
        }
        
        public static string WhatsNewDescription5 {
            get {
                return ResourceManager.GetString("WhatsNewDescription5", resourceCulture);
            }
        }
        
        public static string WhatsNewTitle1 {
            get {
                return ResourceManager.GetString("WhatsNewTitle1", resourceCulture);
            }
        }
        
        public static string WhatsNewTitle2 {
            get {
                return ResourceManager.GetString("WhatsNewTitle2", resourceCulture);
            }
        }
        
        public static string WhatsNewTitle3 {
            get {
                return ResourceManager.GetString("WhatsNewTitle3", resourceCulture);
            }
        }
        
        public static string WhatsNewTitle4 {
            get {
                return ResourceManager.GetString("WhatsNewTitle4", resourceCulture);
            }
        }
        
        public static string WhatsNewTitle5 {
            get {
                return ResourceManager.GetString("WhatsNewTitle5", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsURL {
            get {
                return ResourceManager.GetString("TermsAndConditionsURL", resourceCulture);
            }
        }
        
        public static string StringPickYourTheme {
            get {
                return ResourceManager.GetString("StringPickYourTheme", resourceCulture);
            }
        }
        
        public static string LightThemeString {
            get {
                return ResourceManager.GetString("LightThemeString", resourceCulture);
            }
        }
        
        public static string DarkThemeString {
            get {
                return ResourceManager.GetString("DarkThemeString", resourceCulture);
            }
        }
        
        public static string KubrickThemeString {
            get {
                return ResourceManager.GetString("KubrickThemeString", resourceCulture);
            }
        }
        
        public static string KubrickDarkThemeString {
            get {
                return ResourceManager.GetString("KubrickDarkThemeString", resourceCulture);
            }
        }
        
        public static string CapellaThemeString {
            get {
                return ResourceManager.GetString("CapellaThemeString", resourceCulture);
            }
        }
        
        public static string CapellaDarkThemeString {
            get {
                return ResourceManager.GetString("CapellaDarkThemeString", resourceCulture);
            }
        }
        
        public static string LightThemeDescription {
            get {
                return ResourceManager.GetString("LightThemeDescription", resourceCulture);
            }
        }
        
        public static string DarkThemeDescription {
            get {
                return ResourceManager.GetString("DarkThemeDescription", resourceCulture);
            }
        }
        
        public static string KubrickThemeDescription {
            get {
                return ResourceManager.GetString("KubrickThemeDescription", resourceCulture);
            }
        }
        
        public static string KubrickDarkThemeDescription {
            get {
                return ResourceManager.GetString("KubrickDarkThemeDescription", resourceCulture);
            }
        }
        
        public static string CapellaThemeDescription {
            get {
                return ResourceManager.GetString("CapellaThemeDescription", resourceCulture);
            }
        }
        
        public static string CapellaDarkThemeDescription {
            get {
                return ResourceManager.GetString("CapellaDarkThemeDescription", resourceCulture);
            }
        }
        
        public static string BlackboardThemeDescription {
            get {
                return ResourceManager.GetString("BlackboardThemeDescription", resourceCulture);
            }
        }
        
        public static string BlackSunThemeDescription {
            get {
                return ResourceManager.GetString("BlackSunThemeDescription", resourceCulture);
            }
        }
        
        public static string HazeThemeDescription {
            get {
                return ResourceManager.GetString("HazeThemeDescription", resourceCulture);
            }
        }
        
        public static string CabernetLightThemeDescription {
            get {
                return ResourceManager.GetString("CabernetLightThemeDescription", resourceCulture);
            }
        }
        
        public static string RTLEnabledString {
            get {
                return ResourceManager.GetString("RTLEnabledString", resourceCulture);
            }
        }
        
        public static string RTLEnabledDescription {
            get {
                return ResourceManager.GetString("RTLEnabledDescription", resourceCulture);
            }
        }
        
        public static string NoResultsText {
            get {
                return ResourceManager.GetString("NoResultsText", resourceCulture);
            }
        }
        
        public static string StepsFormPageDescription {
            get {
                return ResourceManager.GetString("StepsFormPageDescription", resourceCulture);
            }
        }
        
        public static string DeliveryWorkflowPageDescription {
            get {
                return ResourceManager.GetString("DeliveryWorkflowPageDescription", resourceCulture);
            }
        }
        
        public static string PreferencesOnboardingPageDescription {
            get {
                return ResourceManager.GetString("PreferencesOnboardingPageDescription", resourceCulture);
            }
        }
        
        public static string SurveyListPageDescription {
            get {
                return ResourceManager.GetString("SurveyListPageDescription", resourceCulture);
            }
        }
        
        public static string CalendarShowcasePageDescription {
            get {
                return ResourceManager.GetString("CalendarShowcasePageDescription", resourceCulture);
            }
        }
        
        public static string BookingReservationPageDescription {
            get {
                return ResourceManager.GetString("BookingReservationPageDescription", resourceCulture);
            }
        }
        
        public static string CalendarSchedulePageDescription {
            get {
                return ResourceManager.GetString("CalendarSchedulePageDescription", resourceCulture);
            }
        }
        
        public static string MediaRankingPageDescription {
            get {
                return ResourceManager.GetString("MediaRankingPageDescription", resourceCulture);
            }
        }
        
        public static string SocialRankingPageDescription {
            get {
                return ResourceManager.GetString("SocialRankingPageDescription", resourceCulture);
            }
        }
    }
}
